INSERT INTO `categories` (`categoryName`) VALUES ('Entree');
INSERT INTO `categories` (`categoryName`) VALUES ('Gllow Box');
INSERT INTO `categories` (`categoryName`) VALUES ('Noodle Soup Bow');
INSERT INTO `categories` (`categoryName`) VALUES ('Rice Dishes');
INSERT INTO `categories` (`categoryName`) VALUES ('Wok Stir Fried');
INSERT INTO `categories` (`categoryName`) VALUES ( 'Main');
INSERT INTO `categories` (`categoryName`) VALUES ( 'Drinks');

/* Entree */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Spring Onion Pancake','',5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Satay Chicken','',7.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Popcorn Chicken', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'XXL Crispy Chicken', '', 9.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Golden Chicken Wing', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Pork Dumpling With Chilli Oil','',8.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Pan Fried Pork Dumpling', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Steam Pork Dumpling', '',8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Pan Fried Vegetarian Dumpling', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Steam Vegetarian Dumpling', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Pork n Prawn Spring Roll', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Vegetarian Spring Roll', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Crispy Sweet Potatoes', '', 8.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Taiwanese Sausage', '', 8.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Wasabi Prawns', '', 9.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Crispy Tofu', '', 11.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Roti Hand Rolls', '', 11.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Oyster Pancake', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Oyster MeeSua Small', '', 7.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Oyster MeeSua Large', '', 10.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Meatball Soup', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Wonton Soup', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,1, 'Veggie Soup', '', 5.50);
/* Gllow Box */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'XXL Crispy Chicken Chop', 'Large tender succulent crispy boneless chicken marinated to perfection.', 13.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Popcorn Chicken', 'Boneless chicken pieces seasonal with sweet chili powder on top.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Chilli Chicken  Spicy', 'Tender chicken wok tossed with dry chilli.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Crispy Fish Fillet', 'Garnished with lemon lime mayo.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Three Cups Chicken', 'Famous Taiwan dish, chicken cook with rice wine, basil, soy sauce and dry chilli.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Teriyaki Salmon', 'Pan fried crispy salmon with teriyaki sauce.', 14.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Salt and Pepper Chicken', 'Succulent deep fried chicken ribs - wok tossed with salt and pepper seasoning.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Golden Chicken Drumstick', 'Marinated with ginger, garlic and spring onion with a thin crispy coating.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Salt and Pepper Squid', 'Marinated squids, deep fried and wok tossed with salt and pepper seasoning.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Teriyaki Chicken', 'Chicken pieces saute with teriyaki sauce.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Teriyaki Beef', 'Beef saute with teriyaki sauce.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Crispy Pork Ribs', 'Deep fried pork cutlet marinated with a traditional Taiwanese style. Served with rice, seasonal dishes in oriental box.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Stir Fry Veggie  Vegetarian', 'Seasonal mixed veggies stir fry with garlic sauce.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Curry Crispy Pork', 'Crispy pork cutlet, serve curry sauce on top.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,2, 'Curry Crispy Chicken', 'Crispy boneless crumbed chicken marinated, serve curry sauce on top.', 13.00);
/* Noodle Soup */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Curry Laksa',  'Signature Dish Vegetarian', 12.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Curry Laksa',  'Signature Dish Chicken', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Curry Laksa',  'Signature Dish Seafood', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Curry Laksa',  'Signature Dish Comination', 13.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Taiwanese Beef Noodle Soup', 'Beef brisket in Chefs special soup with vegetables, herb egg with thick noodle.', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Seafood Noodle Soup', 'Ramen noodle, seafood, vegetable with brown stock.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Crispy Pork Noodle Soup', 'Ramen noodle, seasonal vegetables with crispy pork chop serve on side.', 13.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Crispy Chicken Noodle Soup', 'Ramen noodle, seasonal vegetables with crispy chicken chop serve on side.', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Taiwanese Meatball Noodle Soup', 'Meatball made with pork and mushroom, vermicelli noodle and seasonal vegetables.', 12.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Wonton Noodle Soup', 'Signature Wanton - made with prawn, pork vegetable with egg noodle.', 12.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,3, 'Veggie Noodle Soup', 'Ramen noodle, seasonal vegetables.', 12.00);
/* Rice Dishes */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Sweet and Sour Chicken', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Pork Mince Rice', 'Minced pork stewd in 5 - spice soy broth.',  11.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Teppan Fried Rice', 'Vegetarian fried rice.', 10.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Gllow Fried Rice', 'Choice of seafood chicken or BBQ pork.', 11.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'BBQ Pork', '', 11.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Seafood Fried Rice', 'Fried rice with prawn, squid and fish-cake.', 11.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Combination Fried Rice', 'Fried rice with chicken, BBQ pork and seafoods.', 12.90);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Curry Crispy Pork', 'Deep fried pork cutlet, potato, carrot serve with curry sauce.', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Curry Crispy Chicken', 'Deep fried chicken cutlet, potato, carrot serve with curry sauce.', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Teriyaki Chicken', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Lemon Chicken Rice', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Supreme Pork', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Teriyaki Beef', '', 12.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,4, 'Sweet Sour Fish', '', 12.50);
/* Wok Stir Fried */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,5, 'Taiwan Rice Noodle', 'Stir - fried Taiwan thin rice noodles, shredded pork, mushroom and vegetables.', 11.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,5, 'Fried Koay Teow', 'Rice noodle, prawn, fish - cake, BBQ pork, bean shoot, chives and chilli.', 12.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,5, 'Seafood Stir Fried Noodle', 'Stir - fried Udon noodle, prawn, fish - cake, BBQ pork with dark soy sauce.', 12.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,5, 'Stir Fried Beef Udon', 'Stir - fried Udon noodle, beef, vegetables with seasoning sauce.', 11.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,5, 'Stir Fried Chicken Udon', 'Stir - fried Udon noodle, chicken , vegetables with seasoning sauce.', 11.50);
/* Main */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Threee Cup Chicken', 'Famous Taiwan dish, chicken cook with rice wine, basil, soy sauce and dry chilli.', 19.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Sizzling Tofu', 'Golden homemade tofu, serve with pork mince and shredded mushroom sauce.', 17.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Chilli Chicken', 'Tender chicken wok tossed with dry chilli and homemade chilli sauce.', 18.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Chilli Beef', 'Beef wok tossed with dry chilli and homemade chilli sauce.', 19.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Salt and Pepper Chicken Ribs', 'Succulent deep fried chicken ribs, wok tossed with salt and pepper seasoning.', 19.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Ginger Beef', 'Beef wok tossed with ginger, spring onion, light oyster sauce and seasoning.', 19.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Garlic King Prawns', 'Stir fried king prawns, seasonal vegetables with garlic sauce.', 21.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Salt and Pepper Squid', 'Marinated squid, deep fried and wok tossed with salt and pepper seasoning.', 21.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Crispy Fish Fillet', 'Garnished with lemon lime mayo.', 19.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Terriyaki Salmon', 'Pan fried crispy salmon with teriyaki sauce.', 21.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Chinese Broccoli', 'Topped with oyster sauce.', 15.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Stir Fried Mixed Vegetables', 'Seasonal mixed veggies stir fried with garlic sauce.', 17.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Teriyaki Chicken', 'Stir fried chicken, zucchini, carrot, onion with teriyaki sauce', 18.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,6, 'Teriyaki Beef', 'Stir fried beef, vermicelli, snow pea, zucchini, carrot, onion with teriyaki sauce.', 19.00);
/* Drinks */
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Orange Juice', 'Freshly squeeze orange juice.', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Soft Drinks', 'Coke, Coke Zero, Sprite, Fanta, Lemonade', 3.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Sparkling Mineral Water', 'S. Pelligrino mineral water 500ml', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Sparkling Mineral Water', 'S. Pelligrino mineral water 750ml', 8.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Honeydew', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Original Milk Tea', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Coconut', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Lychee', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Matcha Green Tea', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Passion Fruit', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Strawberry', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Watermelon', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Taro', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Mango', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Mocha', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Red Bean', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Milk Tea Peach', '', 5.00);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Lemon Tea', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Peach', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Passion Fruit', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Strawberry', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Sourplum', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Honey Dew', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Lychee', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Iced Tea Mango', '', 4.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Coconut', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Mango', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Sourplum', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Strawberry', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Passionfruit', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Red Bean', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Matcha Green Tea', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Honeydew', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Lychee', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Mocha', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Peach', '', 5.50);
INSERT INTO `items` (`cafeId`, `categoryId`, `itemName`, `description`, `price`) VALUES (2,7, 'Ice Blended Taro', '', 5.50);
